User.create!([
  {username: "Admin", email: "nathan@gmail.com", password_digest: "$2a$12$NZmRcw/IIvJnl5xlbHVfMeVz3ktwcsuWevcmZ9h1WWgyfi7IhyJeO", renter_id: 1, type: nil, firstname: "nathan", lastname: "doore", dob: "1995-05-03", firstline: "40 pine close", postcode: "LE17 4UR", mobile: 7968668433, terms: "yes", img_url: "man1.jpg", rentcount: 0},
  {username: "Doore", email: "doore@gmail.com", password_digest: "$2a$12$MvHIPNCdF4/PrET85l/VLOr9kHWw/D4eay2qfdNdTNdRP5dYLQKoq", renter_id: 1, type: nil, firstname: "DOORE", lastname: "nathan", dob: "1989-05-03", firstline: "30 nana road", postcode: "LE1 3UT", mobile: 7968668436, terms: "yes", img_url: "man2.jpg", rentcount: 0},
  {username: "Mark", email: "mark@gmail.com", password_digest: "$2a$12$RjNTx1KKfuq5KCpVBpNzru4JjqeE5VWvlRrOfbFiSos.Uz09WwlOi", renter_id: 1, type: nil, firstname: "Mark", lastname: "Smith", dob: "1978-05-03", firstline: "40 pine", postcode: "LE17 4UT", mobile: 7968668439, terms: "yes", img_url: "man.jpg", rentcount: 0}
])
Car.create!([
  {manufacturer: "Audi", model: "R8", fuel: "Petrol", colour: "Red", engine: "5.2", description: "A super car", year: 2020, price: 99, img_url: nil, user_id: 2, pickup: "40 Pine Close", postcode: "LE17 4UT", renter_id: 1, hirestart: nil, hirefinish: nil, doors: nil, transmission: nil, passengers: nil, bootspace: nil, status: nil, request_id: nil, response: nil, rentcount: 0},
  {manufacturer: "Mercades", model: "CLA", fuel: "Petrol", colour: "Grey", engine: "2.0", description: "A new 2019 Mercades", year: 2019, price: 29, img_url: "cla.jpg", user_id: 2, pickup: "60 Orange Street", postcode: "OX9 3UR", renter_id: 1, hirestart: nil, hirefinish: nil, doors: 3, transmission: "Automatic", passengers: 1, bootspace: "Medium", status: nil, request_id: nil, response: nil, rentcount: 0},
  {manufacturer: "Jaguar", model: "F-Type", fuel: "Petrol", colour: "Black", engine: "2.5", description: "A Jag supercar!", year: 2018, price: 59, img_url: "ftype.jpg", user_id: 2, pickup: "20 Clarke Crecent", postcode: "LO1 3UD", renter_id: 1, hirestart: nil, hirefinish: nil, doors: 5, transmission: "Manual", passengers: 4, bootspace: "Small", status: nil, request_id: nil, response: nil, rentcount: 0},
  {manufacturer: "Dacia", model: "Duster", fuel: "Petrol", colour: "Grey", engine: "1.4", description: "A standard runaround", year: 2016, price: 9, img_url: "duster.jpg", user_id: 2, pickup: "11 Duncan Road", postcode: "LE8 3EG", renter_id: 1, hirestart: nil, hirefinish: nil, doors: 5, transmission: "Automatic", passengers: 2, bootspace: "Small", status: nil, request_id: nil, response: nil, rentcount: 0},
  {manufacturer: "Range Rover", model: "Sports", fuel: "Petrol", colour: "Black", engine: "4.0", description: "A Large SUV sports car", year: 2019, price: 49, img_url: "rangerover.jpg", user_id: 2, pickup: "98 Brown road", postcode: "IP1 4PD", renter_id: 1, hirestart: nil, hirefinish: nil, doors: 5, transmission: "Automatic", passengers: 2, bootspace: "Small", status: nil, request_id: nil, response: nil, rentcount: 0},
  {manufacturer: "BMW", model: "I8", fuel: "Petrol", colour: "Blue", engine: "1.6", description: "A hybrid Supercar", year: 2017, price: 59, img_url: "i8.jpg", user_id: 2, pickup: "12 Blaby Street", postcode: "WO9 2HD", renter_id: 1, hirestart: nil, hirefinish: nil, doors: 5, transmission: "Manual", passengers: 1, bootspace: "Large", status: nil, request_id: nil, response: nil, rentcount: 0},
  {manufacturer: "Ford", model: "Fiesta", fuel: "Petrol", colour: "Yellow", engine: "1.0", description: "A nice car for younger drivers", year: 2012, price: 19, img_url: "fiesta.jpg", user_id: 2, pickup: "92 Station Road", postcode: "LE3 7UH", renter_id: 1, hirestart: nil, hirefinish: nil, doors: 3, transmission: "Semi-Auto", passengers: 2, bootspace: "Medium", status: nil, request_id: nil, response: nil, rentcount: 0},
  {manufacturer: "Vauxhall", model: "Astra", fuel: "Petrol", colour: "Black", engine: "1.6", description: "A quick car for all purposed", year: 2013, price: 14, img_url: "astra.jpeg", user_id: 2, pickup: "28 Bolter Crecent", postcode: "PE1 3UR", renter_id: 1, hirestart: nil, hirefinish: nil, doors: 3, transmission: "Manual", passengers: 3, bootspace: "Large", status: nil, request_id: nil, response: nil, rentcount: 0},
  {manufacturer: "Fiat", model: "500", fuel: "Petrol", colour: "Pink", engine: "1.4", description: "A small car for small people", year: 2015, price: 17, img_url: "fiat.jpg", user_id: 2, pickup: "23 Rich Street", postcode: "WA1 2UE", renter_id: 1, hirestart: nil, hirefinish: nil, doors: 3, transmission: "Automatic", passengers: 2, bootspace: "Small", status: nil, request_id: nil, response: nil, rentcount: 0},
  {manufacturer: "Lexus", model: "LS 500", fuel: "Petrol", colour: "Blue", engine: "2.0", description: "A luxury family car", year: 2017, price: 27, img_url: "lexus.jpg", user_id: 2, pickup: "33 Fox Road", postcode: "LO1 2HA", renter_id: 1, hirestart: nil, hirefinish: nil, doors: 5, transmission: "Automatic", passengers: 1, bootspace: "Medium", status: nil, request_id: nil, response: nil, rentcount: 0}
])
